TARGET = iphone:clang:latest:11.0
ARCHS = arm64
GO_EASY_ON_ME = 1

LIBRARY_NAME = libundirect

libundirect_FILES = libundirect.x
libundirect_CFLAGS = -fobjc-arc
libundirect_INSTALL_PATH = /usr/lib

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
